### ISSUE TITLE
error when installing fribidi, seems to be issue with glib

### ISSUE THREAD

**Issue by jonathon-love** [R-macos/recipes#38]
hi,

i'm getting the following error when using `bash build.sh fribidi` under macos 11 (with github actions).

```
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/Authorization.h:193:7: error: variably modified ‘bytes’ at file scope
  char bytes[kAuthorizationExternalFormLength];
       ^~~~~
  CC       gspawn.lo
...
make: *** [pkgconfig-0.29.2-dst] Error 2
Error: Process completed with exit code 2.
```

more details [here](https://github.com/jonathon-love/r-package-snapshot/actions/runs/4627799634/jobs/8186140297)

is there a way i could fix this?

this is the job i'm running:

```
jobs:
  build:
    runs-on: macos-11

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.3'

    - name: Check R version
      run: R.version
      shell: Rscript {0}

    - name: Install R deps
      run: |
        git clone https://github.com/R-macos/recipes
        cd recipes
        sudo bash build.sh fribidi
```

my intention is to have a repo that i can use to build macOS binary packages more-or-less equivalent to those created by CRAN. this was prompted by the shuttering of MRAN snapshots, and i still need to be able to get access to historical R macOS binaries (that neither CRAN, nor rstudio package manager retain). (if someone knows of another project doing this, i'd be keen to hear about it!)

with thanks
